# Generated by Django 4.2.3 on 2023-07-14 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_login_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 10, 13, 54, 580505)),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='user_name',
            field=models.CharField(default=datetime.datetime(2023, 7, 14, 4, 44, 10, 364034, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
    ]
