# Generated by Django 4.2.3 on 2023-07-14 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_login_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 10, 48, 32, 745277)),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='user_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
