# Generated by Django 4.2.2 on 2023-07-17 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_alter_login_login_time_alter_login_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 18, 47, 3, 781906)),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(default='passcode', max_length=30),
        ),
        migrations.AlterField(
            model_name='login',
            name='user_name',
            field=models.CharField(default='user_name', max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
