# Generated by Django 4.2.2 on 2023-07-17 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_alter_login_login_time_alter_login_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 18, 49, 2, 769577)),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
