# Generated by Django 4.2.2 on 2023-07-17 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_alter_login_login_time_alter_register_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 18, 51, 23, 75215)),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default='', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_name',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
