# Generated by Django 4.2.2 on 2023-07-17 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_alter_login_login_time_alter_register_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 18, 52, 35, 660556)),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(default='passcode', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='user_name',
            field=models.CharField(default='user_name', max_length=30, null=True),
        ),
    ]
