# Generated by Django 4.2.2 on 2023-07-17 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_alter_login_login_time_alter_login_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 19, 13, 48, 79279)),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('not to prefer', 'no to prefer')], default='', max_length=20, null=True),
        ),
    ]
