# Generated by Django 4.2.3 on 2023-07-18 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_alter_login_login_time_alter_register_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 9, 25, 5, 879296)),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('not specified', 'not specified')], default='', max_length=20, null=True),
        ),
    ]
