# Generated by Django 4.2.3 on 2023-07-18 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_alter_login_login_time_alter_register_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 11, 7, 53, 608267)),
        ),
    ]
