# Generated by Django 4.2.3 on 2023-07-19 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0028_alter_login_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 12, 46, 29, 195679)),
        ),
    ]
