# Generated by Django 4.2.3 on 2023-07-19 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0030_alter_login_login_time_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 16, 38, 50, 408751)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.ManyToManyField(to='register.login'),
        ),
    ]
