# Generated by Django 4.2.3 on 2023-07-19 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0032_alter_login_login_time_remove_tasks_user_tasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 17, 31, 47, 333434)),
        ),
    ]
