# Generated by Django 4.2.3 on 2023-07-20 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0036_alter_login_login_time_alter_tasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 16, 6, 5, 448186)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.login'),
        ),
    ]
