# Generated by Django 4.2.3 on 2023-07-20 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0038_alter_login_login_time_alter_tasks_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='C:/Users/bdharani/Desktop/task/project/register/uploaded_files')),
                ('file_time', models.DateTimeField(default=datetime.datetime(2023, 7, 20, 16, 42, 12, 267790))),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 16, 42, 12, 266790)),
        ),
    ]
