# Generated by Django 4.2.3 on 2023-07-25 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0039_file_upload_alter_login_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='file_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 9, 43, 40, 57561)),
        ),
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 9, 43, 40, 56563)),
        ),
    ]
