# Generated by Django 4.2.3 on 2023-07-26 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0041_alter_file_upload_file_time_alter_login_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='file_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 10, 52, 56, 727843)),
        ),
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 10, 52, 56, 726845)),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone_number',
            field=models.CharField(default='', max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_name',
            field=models.CharField(default='', max_length=20, null=True, unique=True),
        ),
    ]
