# Generated by Django 4.2.3 on 2023-07-26 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0042_alter_file_upload_file_time_alter_login_login_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='user_name',
            new_name='Email',
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='file_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 11, 55, 6, 611101)),
        ),
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 11, 55, 6, 610060)),
        ),
    ]
