# Generated by Django 4.2.3 on 2023-07-26 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0043_rename_user_name_login_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Email',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='file_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 11, 59, 36, 42116)),
        ),
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 11, 59, 36, 41119)),
        ),
    ]
