# Generated by Django 4.2.3 on 2023-07-28 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0045_alter_file_upload_file_time_alter_login_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='file_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 11, 25, 7, 727730)),
        ),
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 11, 25, 7, 726023)),
        ),
    ]
