# Generated by Django 4.2.3 on 2023-07-28 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0046_alter_file_upload_file_time_alter_login_login_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.CharField(max_length=30, null=True)),
                ('person2', models.CharField(max_length=30, null=True)),
                ('p1_msg', models.TextField(max_length=100, null=True)),
                ('p2_msg', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='file_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 15, 37, 13, 389852)),
        ),
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 15, 37, 13, 387859)),
        ),
    ]
